extend = { path = "../build/common-makefile.toml" }

[env]
PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/tuple_heter_iter"

[tasks.test]
command = "true" # I cannot just use `extend = "cargo-test"`. It does not work.
args = []
dependencies = [ "cargo-test" ]
