[package]
name = "static_error_macro"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true


[dependencies]
syn = "2.0.65"
quote = "1.0.36"
proc-macro2 = "1.0.82"
itertools = "0.13.0"


[dev-dependencies]
thiserror = "1.0.61"
anyhow = "1.0.86"
bigdecimal = "0.4.3"
