[package]
name = "project01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#proc-macro = true

[features]
# Defines a feature named `webp` that does not enable any other features.
#webp = []
#error_generic_member_access = []
#special-integration-test = []

serde_json_raw_value = ["serde_json/raw_value"]
#default = ["serde_json_raw_value", ]


#['cfg(feature = "a")'.lib]
#crate-type = ["staticlib"]
#
#['cfg(feature = "b")'.lib]
#crate-type = ["rlib"]




[build-dependencies]
cargo_metadata = "0.18.1"


[dependencies]
static_error_macro = { version = "0.1.0", path = "static_error_macro" }

# -------------------------------------------------------------------------
if_chain = "1.0.2"

static_assertions = "1.1.0"
const_format = "0.2.32"
bigdecimal = "0.4.3"
#bigdecimal = {  version = "0.4.3", features = ["default", "serde" ] }

serde = { version = "1.0.201", features = ["derive", "std", "rc", "serde_derive" ] }
#serde = "1.0.201"
#serde_json = "1.0.117"
#serde_json = { version = "1.0.117", features = ["default", ] }
#serde_json = { version = "1.0.117", features = ["default", "raw_value", ] }
serde_json = { version = "1.0.117", features = ["default", ] }
#serde_json5 = "0.1.0
#serde_as = "0.0.1"
serde_with = "3.8.1"
serde_with_macros = "3.8.1"

anyhow = { version = "1.0.83", features = ["backtrace"] }
#anyhow = { version = "1.0.83"} # , features = ["backtrace"] } // it means third-party "backtrace"
thiserror = "1.0.60"
#snafu = "0.8.2"
indoc = "2.0.5"

## !!! Out dated !!!
## !!! backtrace = "0.3.71"

strum = "0.26"
strum_macros = "0.26"

# # Seems it does not work.
# color-backtrace = "0.6.1"

derivative = "2.2.0"

ctor = "0.2.8"
once_cell = "1.19.0"
#lazy_static = "1.4.0"
static_init = "1.0.3"

log = "0.4.21"
env_logger = "0.11.3"
log4rs = "1.3.0"

dotenv = "0.15.0"

inherent = "1.0.11"
readonly = "0.2.12"
extension-trait = "1.0.2"

chrono = {  version = "0.4.38", features = ["default", "serde"] }
chrono-tz = "0.9.0"
time = "0.3.36"

#type-rules = { version = "0.2.3", features = ["derive", "regex", "serde"] }
type-rules = { version = "0.2.3", features = ["derive", "regex"] }

axum = "0.7.5"
#tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread"] }
#tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio = { version = "1.38.0", features = ["full"] }
#bytes = "1.6.0"

# unused manifest key: tests
#[test]
[tests]

#autotests = false
#
#[[test]]
#name = "test_token_trees"
#path = "tests/test_token_trees.rs"
#
#[[test]]
#name = "test_parse_buffer"
#path = "tests/test_parse_buffer.rs"



[dev-dependencies]
#mockall = "0.12.1"
#test-case = "3.3.1"
#test-case = "2.2.2"
test-case = "*"
assertables = "7.0.1"

#assert_json = "0.1.0"
assert-json-diff = "2.0.2"
#jsondiff = "0.1.0"

#assert-str = "0.1.0"
#assert-text = "0.2.9"
#assert_eq_all = "0.1.1"
#assert_fn = "1.0.7"
#assert_json = "0.1.0" // requires 'thiserror v1.0.60 (*)'
#assert-call = "0.1.1"
#assert_no_alloc = "1.1.2"
#assert_approx_eq = "1.1.0"
#assert_that = "0.1.2"
#assert_panic_free = "1.0.2"
#assert_matches = "1.5.0"

# # Seems it does not work.
# color-backtrace = "0.6.1"
# ctor = "0.2.8"

macro_rules_attribute = "0.2.0"

# hm... unused manifest key: benches
[benches]

#autobenches = false
#
#[[bench]]
#name = "rust"
#path = "benches/rust.rs"
#harness = false
#required-features = [
#    "full",
#    "parsing",
#]
#
#[[bench]]
#name = "file"
#path = "benches/file.rs"
#required-features = [
#    "full",
#    "parsing",
#]




[workspace]
members = [
    "static_error_macro",
]
