[package]
name = "project01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#proc-macro = true

[dependencies]
static_assertions = "1.1.0"
const_format = "0.2.32"
bigdecimal = "0.4.3"

# unused manifest key: tests
#[test]
[tests]


[dev-dependencies]
#mockall = "0.12.1"
#test-case = "3.3.1"
#test-case = "2.2.2"
test-case = "*"


# hm... unused manifest key: benches
[benches]


[workspace]
members = [
    "other01",
]
