
[workspace]
members = [
    "tuple_heter_iter_macro",
    "tuple_heter_iter",
    "proc_macro",
    "static_error_macro",
    "auth",
    "common",
    "account_soa",
]
#resolver = "1"
resolver = "2"
