
[workspace]
members = [
    "_subpackages/tuple_heter_iter_macro",
    "_subpackages/tuple_heter_iter",
    "_subpackages/static_error_macro",
    "_subpackages/mvv_auth",
    "_subpackages/mvv_common",
    "_subpackages/account_soa",
]
#resolver = "1"
resolver = "2"
