#[tasks.format]
#install_crate = "rustfmt"
#command = "cargo"
#args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

#[tasks.build]
#command = "cargo"
#args = ["build"]
##dependencies = ["clean"]
#dependencies = []

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.my-flow]
script = "echo \"Fucking cargo make!!! (from my-flow)\""
workspace = false
dependencies = [
    #"format",
    "build",
    "test"
]

[tasks.myflow]
alias = "my-flow"

[tasks.docker-build]
command = "docker"
args = ["build", "--file", "docker/Dockerfile", "--tag", "rust-mvv-webapp-02", ".",]
workspace = false
dependencies = [
    #"format",
    "build",
    "test"
]

[tasks.docker_build]
alias = "docker-build"
