
networks:
  rust-account-soa-net:
    name: account-web-it-tests

services:
  rust-account-soa:
    # We can use 'extends' if we use docker-compose (swarm) in production
    # and want just inherit prod docker compose file.
    #
    # extends:
    #  service: account-soa
    #  file: ${BASE_DIR}/../account-soa/src/main/docker/docker-compose.yml
    #
    # image: ${DOCKER_IMAGE_PREFIX}rust-mvv-webapp-debug # mvv-registry/mvv.bank/pseudo2-account-soa
    image: mvv_rust_account_soa${DOCKER_IMAGE_PROFILE_SUFFIX}
    networks:
      - rust-account-soa-net
    environment:
      # - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n

      - SERVER_PORT=8443
      # - SERVER_CONTEXTPATH=/account-soa

      - POSTGRES_HOST=database
      - POSTGRES_DB=rust_mvvbank
      - POSTGRES_USER=rust_mvvbank
      - POSTGRES_PASSWORD=psw

      - SERVER_SSL_KEY_PATH=/certs/rust-account-soa.key.pem
      - SERVER_SSL_CERT_PATH=/certs/rust-account-soa.crt.pem
      # SOA dependencies
      #- POSTGRES_SSL_CERT_PATH=/certs/database.crt.pem  # database.crt.pem can be used with PgSslMode::Require
      - POSTGRES_SSL_CERT_PATH=/certs/ca.crt.pem  # CA should be used if PgSslMode::VerifyCa or PgSslMode::VerifyFull is used
    volumes:
      - ../target/generated-test-resources/ssl/:/certs/:ro
    ports:
      # DOCKER_HOST_ACCOUNT_SOA_PORT_WITH_COLON=8095:
      - 8101:8443
      # Remote debug
      # - ${DOCKER_HOST_DEBUG_ACCOUNT_SOA_PORT_WITH_COLON}8000
    links:
      - database:db_postgres
    depends_on:
      - database
    deploy:
      #replicas: ${DOCKER_COMPOSE_SCALE_REPLICA_COUNT}
      replicas: 1
    stop_grace_period: 1s


  rust-client-search-soa:
    # We can use 'extends' if we use docker-compose (swarm) in production
    # and want just inherit prod docker compose file.
    #
    # extends:
    #  service: account-soa
    #  file: ${BASE_DIR}/../account-soa/src/main/docker/docker-compose.yml
    #
    # image: ${DOCKER_IMAGE_PREFIX}rust-mvv-webapp-debug # mvv-registry/mvv.bank/pseudo2-account-soa
    image: mvv_rust_client_search_soa${DOCKER_IMAGE_PROFILE_SUFFIX}
    networks:
      - rust-account-soa-net
    environment:
      # - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n

      - SERVER_PORT=8443
      # - SERVER_CONTEXTPATH=/account-soa

      - POSTGRES_HOST=database
      - POSTGRES_DB=rust_mvvbank
      - POSTGRES_USER=rust_mvvbank
      - POSTGRES_PASSWORD=psw
      #- POSTGRES_SSL_CERT_PATH=/certs/database.crt.pem  # database.crt.pem can be used with PgSslMode::Require
      - POSTGRES_SSL_CERT_PATH=/certs/ca.crt.pem  # CA should be used if PgSslMode::VerifyCa/VerifyFull is used

      - SERVER_SSL_KEY_PATH=/certs/rust-client-search-soa.key.pem
      - SERVER_SSL_CERT_PATH=/certs/rust-client-search-soa.crt.pem
    volumes:
      - ../target/generated-test-resources/ssl/:/certs/:ro
    ports:
      # DOCKER_HOST_ACCOUNT_SOA_PORT_WITH_COLON=8095:
      - 8103:8443
      # Remote debug
      # - ${DOCKER_HOST_DEBUG_ACCOUNT_SOA_PORT_WITH_COLON}8000
    links:
      - database:db_postgres
    depends_on:
      - database
    deploy:
      #replicas: ${DOCKER_COMPOSE_SCALE_REPLICA_COUNT}
      replicas: 1
    stop_grace_period: 1s


  rust-account-web:
    # We can use 'extends' if we use docker-compose (swarm) in production
    # and want just inherit prod docker compose file.
    #
    # extends:
    #  service: account-soa
    #  file: ${BASE_DIR}/../account-soa/src/main/docker/docker-compose.yml
    #
    #image: ${DOCKER_IMAGE_PREFIX}rust-mvv-webapp-debug # mvv-registry/mvv.bank/pseudo2-account-soa
    image: mvv_rust_account_web${DOCKER_IMAGE_PROFILE_SUFFIX}
    networks:
      - rust-account-soa-net
    environment:
      # - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n

      - SERVER_PORT=8443
      # - SERVER_CONTEXTPATH=/account-web

      - POSTGRES_HOST=database
      - POSTGRES_DB=rust_mvvbank
      - POSTGRES_USER=rust_mvvbank
      - POSTGRES_PASSWORD=psw
      #- POSTGRES_SSL_CERT_PATH=/certs/database.crt.pem  # database.crt.pem can be used with PgSslMode::Require
      - POSTGRES_SSL_CERT_PATH=/certs/ca.crt.pem  # CA should be used if PgSslMode::VerifyCa/VerifyFull is used

      - SERVER_SSL_KEY_PATH=/certs/rust-account-web.key.pem
      - SERVER_SSL_CERT_PATH=/certs/rust-account-web.crt.pem

      # SOA Dependencies
      - DEPENDENCIES_ACCOUNT_SOA_REST_BASE_URLS=https://rust-account-soa:8443
      #- DEPENDENCIES_ACCOUNT_SOA_SERVER_SSL_CERT_PATH=/certs/rust-account-soa.crt.pem  # use it in simple self-signed key/cert generated
      - DEPENDENCIES_ACCOUNT_SOA_CA_SSL_CERT_PATH=/certs/ca.crt.pem  # use CA if CA was used for generated server key/cert
      - DEPENDENCIES_ACCOUNT_SOA_USER=vovan-read
      - DEPENDENCIES_ACCOUNT_SOA_PSW=qwerty

      - DEPENDENCIES_CLIENT_SEARCH_SOA_GRPC_BASE_URLS=https://rust-client-search-soa:8443
      # Actually CA cert is used by tonic client now, but both are passed (if present).
      - DEPENDENCIES_CLIENT_SEARCH_SOA_CA_SSL_CERT_PATH=/certs/ca.crt.pem
      - DEPENDENCIES_CLIENT_SEARCH_SOA_SERVER_SSL_CERT_PATH=/certs/rust-client-search-soa.crt.pem
      - DEPENDENCIES_CLIENT_SEARCH_SOA_USER=vovan-read
      - DEPENDENCIES_CLIENT_SEARCH_SOA_PSW=qwerty
    volumes:
      - ../target/generated-test-resources/ssl/:/certs/:ro
    ports:
      - 8102:8443  # DOCKER_HOST_ACCOUNT_SOA_PORT_WITH_COLON=8095:
      # - ${DOCKER_HOST_DEBUG_ACCOUNT_SOA_PORT_WITH_COLON}8000
    links:
      - database:db_postgres
    depends_on:
      - database
      - rust-account-soa
    deploy:
      #replicas: ${DOCKER_COMPOSE_SCALE_REPLICA_COUNT}
      replicas: 1
    stop_grace_period: 1s


  database:
    image: postgres:16
    networks:
      - rust-account-soa-net
    hostname: database # required only for fabricio8 plugin
    # -l - enable SSL connections
    # T O D O: how disable plain TCP connection; `-c listen_addresses=''` blocks everything.
    # entrypoint: docker-entrypoint.sh postgres -l -c ssl=on -c ssl_cert_file=/certs/database.crt.pem -c ssl_key_file=/certs/database.key.pem -c listen_addresses=''
    command: sh -c "
         cp /certs/database.key.pem /usr/lib/ssl/database-test.key.pem &&
         chown postgres /usr/lib/ssl/database-test.key.pem &&
         chmod go-r /usr/lib/ssl/database-test.key.pem &&
         docker-entrypoint.sh postgres -l -c ssl=on -c ssl_cert_file=/certs/database.crt.pem -c ssl_key_file=/usr/lib/ssl/database-test.key.pem
      "
    environment:
      POSTGRES_DB: rust_mvvbank
      POSTGRES_USER: rust_mvvbank
      POSTGRES_PASSWORD: psw
    ports:
      - 5432:5432  # - ${DOCKER_HOST_POSTGRES_DB_PORT_WITH_COLON}5432
    volumes:
      - ./../account_soa/test_resources/postgres/init/:/docker-entrypoint-initdb.d/:ro
      - ../target/generated-test-resources/ssl/:/certs/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 6
    deploy:
      replicas: 1
    stop_grace_period: 1s


#  apache-proxy:
#    image: httpd:2.4.51-alpine3.15
#    networks:
#      - rust-account-soa-net
#    ports:
#      - ${DOCKER_HOST_APACHE_PROXY_PORT_WITH_COLON}443
#    volumes:
#      - ./src/main/docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
#      - ./src/main/docker/apache/extra/httpd-ssl-mvv-root-bank.conf:/usr/local/apache2/conf/extra/httpd-ssl-mvv-root-bank.conf
#      - ./target/generated-test-resources/certs/dev-self-signed/:/certs/
#    deploy:
#      replicas: 1
