#ARG UBUNTU_VERSION=22.04
ARG UBUNTU_VERSION
# Your desktop version should be used.
# Otherwise you will need to add configuration steps for compatibility with
# local built exe file.
#
FROM ubuntu:${UBUNTU_VERSION}

ARG RUN_RUST_BACKTRACE=full

EXPOSE 80 8080 443 8443 8000 2735

LABEL rust-test-label-03=value-3

RUN apt-get -qq update &&                       \
    # apt-get -qq install openssl               \
    # apt-get -qq install iputils-ping &&       \
    # apt-get -qq install curl &&               \
    apt-get -qq update && apt-get -qq install libssl-dev

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "10001" \
    appuser
USER appuser


COPY target/debug/mvv_account_web      ./bin/
COPY target/debug/health_checker       ./bin/
COPY target/debug/http_health_checker  ./bin/

ENV RUST_BACKTRACE=$RUN_RUST_BACKTRACE
ENTRYPOINT ["/bin/mvv_account_web", "arg1", "arg2"]

# good param  --start-interval=2s is unstable ?!
HEALTHCHECK --start-period=5s --interval=5s --timeout=3s --retries=6 CMD health_checker https://localhost:${SERVER_PORT}/healthcheck || exit 1
