
extend = [
    { path = "../build/common-makefile.toml" },
    { path = "../build/ssl-certs-makefile.toml" },
    { path = "../build/docker-build-makefile.toml" },
    { path = "../build/docker-compose-makefile.toml" },
]


[env]
SOA_EXECUTABLE = "mvv_client_search_soa"
DOCKER_IMAGE_TAG = "mvv_rust_client_search_soa"
DOCKER_IMAGE_TARGET = "mvv_rust_client_search_soa"
# Used mainly for dev testing and as base-name for integration tests
DOCKER_COMPOSE_PROJECT_NAME = "rust-client-search-soa-project"

#ROOT_PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/client_search_grpc_soa"



# -----------------------------------------------------------------------------

[tasks.test]
extend = "cargo-test"
dependencies = [
    "build",
    "generate-ssl-certs",
]



[tasks.package] # It is named just according to 'java'
command = "echo" # overriding/disabling predefined build command
args = [ "package flow" ]
dependencies = [
    "build",
    "test",
    "build-docker",
    # "integration-tests",
]
