FROM rust:1.78.0-slim-bullseye AS build

EXPOSE 80 8080 443 8443 8000 2735 3000

LABEL rust-test-label-02=value-2


# View app name in Cargo.toml
#ARG APP_NAME=mvv_temp

#WORKDIR /app
WORKDIR /build

# Reuse cache layer to build faster

#COPY . .

COPY Cargo.lock Cargo.toml build.rs ./

RUN    mkdir ./src                              \
    && mkdir ./src/bin                          \
    && mkdir ./static_error_macro               \
    && mkdir ./static_error_macro/src           \
    && echo "fn main() { }" > ./src/bin/main.rs \
    && echo "// dummy file" > ./src/lib.rs      \
    && echo "// dummy file" > ./static_error_macro/src/lib.rs
COPY static_error_macro/Cargo.lock static_error_macro/Cargo.toml ./static_error_macro/

# Build the dependencies without the actual source code to cache dependencies separately
RUN    cargo check --release --workspace --all-targets --all-features \
    && cargo build --release --workspace

RUN rm ./src/*.rs && rm ./src/bin/*.rs && rm ./static_error_macro/src/*.rs

COPY src/ ./src/
#RUN ls --recursive ./src/
COPY static_error_macro/src/ ./static_error_macro/src/
RUN    touch ./src/lib.rs \
    && touch ./static_error_macro/src/lib.rs

RUN #cargo build --release --workspace --manifest-path ./static_error_macro/Cargo.toml
RUN cargo build --release --workspace
RUN cp ./target/release/web_main_1 /bin/web_main_1

RUN cp ./target/release/web_main_1 /bin/web_main_1

##ENV ROCKET_ADDRESS=0.0.0.0
#CMD ["/bin/web_main_1"]
#ENTRYPOINT /bin/web_main_1 arg1 arg2

FROM debian:bullseye-slim AS final
COPY --from=build /bin/web_main_1 /bin/
#ENV ROCKET_ADDRESS=0.0.0.0
#CMD ["/bin/server"]
ENTRYPOINT ["/bin/web_main_1", "arg1", "arg2"]

# interval=1m
#HEALTHCHECK --interval=5s --timeout=3s CMD wget --quiet --no-check-certificate --tries=1 --spider https://localhost/${PROJECT_CONTEXT_PATH}/api/ping || exit 1
