
extend = [
    { path = "../build/common-makefile.toml" },
    { path = "../build/ssl-simple-certs-makefile.toml" },
    { path = "../build/ssl-ca-certs-makefile.toml" },
    { path = "../build/ssl-certs-makefile.toml" },
    { path = "../build/docker-build-makefile.toml" },
    { path = "../build/docker-compose-makefile.toml" },
    { path = "../build/ssl-ca-certs-openssl3-makefile.toml" },
]

[env]
SOA_EXECUTABLE = "mvv_account_web"
DOCKER_IMAGE_TAG = "mvv_rust_account_web"
DOCKER_COMPOSE_PROJECT_NAME = "rust-account-web-project"

#ROOT_PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/account_web"



# -----------------------------------------------------------------------------
