[alias]
xtask = "run --package xtask --"
#xtask = "run --manifest-path ./xtask/Cargo.toml --"


#
# Code coverage
#

# Build the profiler runtime (required when compiling with options that depend
# on this runtime, such as `-C profile-generate` or `-C instrument-coverage`).
profiler = true
