
extend = [
    { path = "../build/common-makefile.toml" },
    { path = "../build/ssl-certs-makefile.toml" },
    { path = "../build/docker-build-makefile.toml" },
    { path = "../build/docker-compose-makefile.toml" },
]


[env]
SOA_EXECUTABLE = "mvv_account_soa"
DOCKER_IMAGE_TAG = "mvv_rust_account_soa"
DOCKER_IMAGE_TARGET = "mvv_rust_account_soa"
DOCKER_COMPOSE_PROJECT_NAME = "rust-account-soa-project"

#ROOT_PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/account_soa"



# -----------------------------------------------------------------------------

# Overriding 'build' to add 'generate-open-api' to build flow.
[tasks.build]
command = "echo" # overriding/disabling predefined build command
args = [ "build flow" ]
dependencies = [
    "pre-build",
    "rs-compile",
    "generate-ssl-certs",
    "generate-open-api",
    "post-build",
]



[tasks.test]
command = "true" # I cannot just use `extend = "cargo-test"`. It does not work.
args = []
dependencies = [ "cargo-test" ]



[tasks.package] # It is named just according to 'java'
command = "echo" # overriding/disabling predefined build command
args = [ "package flow" ]
dependencies = [
    "build",
    "test",
    "build-docker",
    "integration-tests",
]

#------------------------------------------------------------------------------------------

# Overriding 'build' to add 'generate-open-api' to build flow.
[tasks.build-with-coverage]
command = "echo" # overriding/disabling predefined build command
args = [ "build flow" ]
dependencies = [
    "init-code-coverage",
    "pre-build",
    "rs-compile",
    "rs-test-compile",
    "generate-ssl-certs",
    "generate-open-api",
    "post-build",
]


[tasks.test-with-coverage]
command = "true" # I cannot just use `extend = "cargo-test"`. It does not work.
args = []
dependencies = [
    "init-code-coverage",
    "cargo-test",
]


[tasks.package-with-coverage] # It is named just according to 'java'
command = "echo" # overriding/disabling predefined build command
args = [ "package flow" ]
dependencies = [
    "init-code-coverage",
    "build-with-coverage",
    "test-with-coverage",
    # "build-docker-with-coverage",
    "build-docker-debug-local-with-coverage",
    "integration-tests-with-coverage",
]


########################################################################################################################
#                                         Optional aliases                                                             #
########################################################################################################################
