
extend = [
    { path = "../build/common-makefile.toml" },
    { path = "../build/ssl-simple-certs-makefile.toml" },
    { path = "../build/ssl-ca-certs-makefile.toml" },
    { path = "../build/ssl-certs-makefile.toml" },
    { path = "../build/docker-build-makefile.toml" },
    { path = "../build/docker-compose-makefile.toml" },
]

[env]
SOA_EXECUTABLE = "mvv_account_soa"
DOCKER_IMAGE_TAG = "mvv_rust_account_soa"
DOCKER_COMPOSE_PROJECT_NAME = "rust-account-soa-project"

#ROOT_PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
PROJECT_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/account_soa"



# -----------------------------------------------------------------------------

# Overriding 'build' to add 'generate-open-api' to build flow.
[tasks.build]
command = "echo" # overriding/disabling predefined build command
args = [ "build flow" ]
dependencies = [
    "pre-build",
    "rs-compile",
    "generate-open-api",
    "post-build",
]



[tasks.test]
extend = "cargo-test"
dependencies = [
    "build",
    "generate-ssl-certs",
]



########################################################################################################################
#                                         Optional aliases                                                             #
########################################################################################################################
